image: archlinux
packages:
  - git
sources:
  - https://git.sr.ht/~jmr/dotfiles
secrets:
  # github mirror key
  - 63775cc6-6340-439b-8ef1-6ccac34768dd
environment:
  GIT_SSH_COMMAND: >-
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
tasks:
  - sync-to-github: |
      cd dotfiles
      git push git@github.com:jackrosenthal/dotfiles HEAD:master
